# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfselect < Formula
  desc "The tfselect command lets you select terraform versions."
  homepage "https://basti0nz.github.io/tfselect"
  version "0.1.11"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/basti0nz/tfselect/releases/download/0.1.11/tfselect_0.1.11_darwin_amd64.tar.gz"
    sha256 "8a9caf31b7df6557570ba98a78e74f756ff0b96e7fb80f62ec857f36084ca9d3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/basti0nz/tfselect/releases/download/0.1.11/tfselect_0.1.11_linux_amd64.tar.gz"
    sha256 "244d6e91a792f6d017e61c843b717862fe5146e282b0f9b7244161eb4c7e0af0"
  end

  conflicts_with "terraform"

  def install
    bin.install "tfselect"
  end

  def caveats; <<~EOS
    Type 'tfselect' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on MacOs and Linux
  EOS
  end

  test do
    system "#{bin}/tfselect --version"
  end
end
